FROM gradle:8.10.1-jdk17 AS test-runner
WORKDIR /app

# кэш зависимостей
COPY build.gradle settings.gradle* ./
COPY gradle ./gradle
RUN gradle --no-daemon clean build -x test || true

# исходники
COPY src ./src
COPY gradlew ./
RUN chmod +x gradlew || true

CMD ["gradle", "--no-daemon", "test"]
